module.exports.bookService = require("./book.service")
module.exports.userService = require("./user.service")
module.exports.tokenService = require("./token.service")
module.exports.movieService = require("./movie.service")
module.exports.showService = require("./show.service")
module.exports.bookingService = require("./booking.service")