module.exports.User = require("./user.model")
module.exports.Movie = require("./movie.model")
module.exports.Booking = require("./booking.model")
module.exports.Token = require("./token.model")
module.exports.Show = require("./show.model")
